spring.docker.compose.lifecycle-management=start_only

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security=DEBUG

# Disabled Thymeleaf caching for live reload
spring.thymeleaf.cache=false