spring.application.name=exercise2025
spring.threads.virtual.enabled=true
#spring.datasource.url=jdbc:mysql://192.109.1.102
#spring.datasource.username=${DATABASE_USER:user}
#spring.datasource.password=${DATABASE_PASSWORD:password}