spring.application.name=exercise2025
spring.threads.virtual.enabled=true
spring.datasource.url=jdbc:mysql://mysql:3306/spring
spring.datasource.username=${DATABASE_USER:user}
spring.datasource.password=${DATABASE_PASSWORD:secret}
spring.flyway.locations=classpath:db/migration
